runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.+\.js)
  static_files: dist/mortgage-test/\1
  upload: dist/mortgage-test/(.+\.js)

- url: /(.+\.css)
  static_files: dist/mortgage-test/\1
  upload: dist/mortgage-test/(.+\.css)

- url: /(.+\.png)
  static_files: dist/mortgage-test/\1
  upload: dist/mortgage-test/(.+\.png)

- url: /(.+\.jpg)
  static_files: dist/mortgage-test/\1
  upload: dist/mortgage-test/(.+\.jpg)

- url: /(.+\.svg)
  static_files: dist/mortgage-test/\1
  upload: dist/mortgage-test/(.+\.svg)

- url: /favicon.ico
  static_files: dist/mortgage-test/favicon.ico
  upload: dist/mortgage-test/favicon.ico

- url: /(.+\.json)
  static_files: dist/mortgage-test/\1
  upload: dist/mortgage-test/(.+\.json)

- url: /(.+)
  static_files: dist/mortgage-test/index.html
  upload: dist/mortgage-test/index.html

- url: /
  static_files: dist/mortgage-test/index.html
  upload: dist/mortgage-test/index.html